//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IncidentesBlazor.Module.BusinessObjects.Incidentes
{

    public partial class HistorialIncidente : Base
    {
        Incidente fIncidente;
        [Association(@"HistorialIncidenteReferencesIncidente")]
        public Incidente Incidente
        {
            get { return fIncidente; }
            set { SetPropertyValue<Incidente>(nameof(Incidente), ref fIncidente, value); }
        }
        string fComentario;
        public string Comentario
        {
            get { return fComentario; }
            set { SetPropertyValue<string>(nameof(Comentario), ref fComentario, value); }
        }
    }

}
