//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IncidentesBlazor.Module.BusinessObjects.Incidentes
{

    public partial class Incidente : Base
    {
        Prioridad fPrioridad;
        public Prioridad Prioridad
        {
            get { return fPrioridad; }
            set { SetPropertyValue<Prioridad>(nameof(Prioridad), ref fPrioridad, value); }
        }
        Departamento fDepartamento;
        public Departamento Departamento
        {
            get { return fDepartamento; }
            set { SetPropertyValue<Departamento>(nameof(Departamento), ref fDepartamento, value); }
        }
        string fTitulo;
        public string Titulo
        {
            get { return fTitulo; }
            set { SetPropertyValue<string>(nameof(Titulo), ref fTitulo, value); }
        }
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        DateTime fFechaCierre;
        public DateTime FechaCierre
        {
            get { return fFechaCierre; }
            set { SetPropertyValue<DateTime>(nameof(FechaCierre), ref fFechaCierre, value); }
        }
        string fComentarioCierre;
        public string ComentarioCierre
        {
            get { return fComentarioCierre; }
            set { SetPropertyValue<string>(nameof(ComentarioCierre), ref fComentarioCierre, value); }
        }
        [Association(@"HistorialIncidenteReferencesIncidente")]
        public XPCollection<HistorialIncidente> HistorialIncidentes { get { return GetCollection<HistorialIncidente>(nameof(HistorialIncidentes)); } }
    }

}
