//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace IncidentesBlazor.Module.BusinessObjects.Incidentes
{

    public partial class Sla : Base
    {
        string fDescripcion;
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        int fCantidadHoras;
        public int CantidadHoras
        {
            get { return fCantidadHoras; }
            set { SetPropertyValue<int>(nameof(CantidadHoras), ref fCantidadHoras, value); }
        }
    }

}
